### ISSUE TITLE
Create a program to count the occurrences of each word in a given sentences.

### ISSUE THREAD

**Issue by Sayak-Karar-2581** [printf-twinkle/hacktoberfest-contribute#17]
Write a program in Java, C, C++ or Python to count the frequency of each word in a given sentence.

**Sample Input**
learning python is fun and python is powerful

**Sample Output**
learning=1
python=2
is=2
fun=1
and=1
powerful=1

**Comment by plavani0208** [comment]
Can you assign this issue to me?

**Comment by plavani0208** [comment]
Can you assign this to me?

**Comment by ShouryaBrahmastra** [comment]
Would like to do this in c languague can you please assign me this

**Comment by Arko017** [comment]
I can do this in java.......shall I do it ???

**Comment by Amdbase1** [comment]
Hi, I would like to contribute to this, Please assign this issue to me.

**Comment by Aniruddha775** [comment]
Hi, I would also like to contribute, Please assign me in this issue

**Comment by Mayankjha997** [comment]
Hello @printf-twinkle ;
can i do this problem in python, please assign me this issue

**Comment by parthib01** [comment]
please assign me this one, I would like to do it.

**Comment by aark06** [comment]
I'd like to work on this issue in Java. Please assign it to me.

**Comment by ameeetgaikwad** [comment]
I can do it in java, can you assign it to me?
