### ISSUE TITLE
Write a basic code snippet for displaying "I am participating in Hacktoberfest 2021" on the webpage

### ISSUE THREAD

**Issue by printf-twinkle** [printf-twinkle/hacktoberfest-contribute#2]
This task must be completed using HTML language, you may use CSS if required.

**Comment by DanDias00** [comment]
Hi im a newbie. Can i work on this issue?

**Comment by harshalkh** [comment]
@printf-twinkle I have raised PR. #4

**Comment by printf-twinkle** [comment]
@DanDias00 yes you may, check the existing index.html file and make changes to that please!

**Comment by DanDias00** [comment]
> @DanDias00 yes you may, check the existing index.html file and make changes to that please!

Hi, I have fulfilled it!
