### ISSUE TITLE
Check if a number entered by the user is prime or not

### ISSUE THREAD

**Issue by printf-twinkle** [printf-twinkle/hacktoberfest-contribute#3]
You may use any language of choice but preferrably in C, Java or Python.

**Steps to consider following**: 
```
1) Take user input
2) Run a loop
3) Check if prime or not
4) Display appropriate message
```

**Comment by RiyaBhandari-2811** [comment]
I want to work on these issue , pls assign these to me , i would be very happy to work on these issue :-)

**Comment by RiyaBhandari-2811** [comment]
Ma'am I've Solved Your Issue #3 In JAVA language , If you found my solution helpful and genuine pls merge my PR .

**Comment by DanDias00** [comment]
Hi i have solved issue and submitted pull request.....please consider it if its useful

**Comment by printf-twinkle** [comment]
I have accepted the PRs that were fine, others please check the existing files and make changes or create new issues

**Comment by printf-twinkle** [comment]
@RiyaBhandari-2811 added your PR

**Comment by Aniruddha775** [comment]
I also want to contribute to this issue..C Language

**Comment by RiyaBhandari-2811** [comment]
Thank you so much 💯💯😊

**Comment by printf-twinkle** [comment]
@Aniruddha775 you may submit a PR , if it's fine, I will merge it!!

**Comment by Aniruddha775** [comment]
> @Aniruddha775 you may submit a PR , if it's fine, I will merge it!!

Sumbitted.

**Comment by kmr-sahil** [comment]
import java.util.*;
class prime
{
public static void main()
{
Scanner sc=new Scanner(System.in);
int n=0;
n=sc.nextInt();
if(n%2==0)
{
System.out.println("The Number is even");
}
else
{
System.out.println("The Number is even");
}
}
}

**Comment by Himanshusharma1105** [comment]
i have been learning java for a long time....i want to practice some programmes using java..Please assign me

**Comment by KanailalManna** [comment]
I want to work on it

**Comment by manish866** [comment]
Please assign me I will do it in java

**Comment by printf-twinkle** [comment]
Java programs will be uploaded next, please be active on this repo! @manish866 @KanailalManna @Himanshusharma1105 @kmr-sahil

**Comment by dhirajgupta12** [comment]
I start learning the java programming language a few months ago. I want to practice this program. Please assign me. I'll give my best.

**Comment by swapnajitsaha** [comment]
Please assign me. I will try it in c.
